[package]
name = "bitray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.25.0"
image = "0.24.8"
rand = "0.8.5"
rayon = "1.8.1"
russimp = "3.2.0"

[features]
f64 = []